name: Crear imagen, realizar pruebas unitarias y desplegar en ACI (automatizado)

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: topicosregistry2.azurecr.io
  AZURE_RESOURCE_GROUP: topicos-rg
  AZURE_ACI_NAME: api-topicos-container
  AZURE_ACI_REGION: eastus

jobs:
  crear-testear-desplegar:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4

    - name: Autenticarse en Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Instalar dependencias de Python
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Ejecutar pruebas unitarias
      env:
        DB_CONNECTION_STRING: "dummy_connection_string"
      run: |
        echo "--- Ejecutando pruebas unitarias (Python) ---"
        pytest || exit 1
        echo "Pruebas unitarias finalizadas."

    - name: Conectarse a ACR
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Crear y hacerle push a la imagen Docker hacia el ACR
      run: |
        docker build . -t ${{ env.AZURE_CONTAINER_REGISTRY }}/api-topicos:latest
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/api-topicos:latest

    - name: Desplegar/Actualizar instancia ACI
      id: deploy-aci
      run: |
        echo "--- Eliminando instancia ACI existente (si la hay) ---"
        az container delete \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name ${{ env.AZURE_ACI_NAME }} \
          --yes || true

        echo "--- Creando/Actualizando instancia ACI con la nueva imagen ---"
        az container create \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name ${{ env.AZURE_ACI_NAME }} \
          --image ${{ env.AZURE_CONTAINER_REGISTRY }}/api-topicos:latest \
          --dns-name-label myflaskapp-uni2 \
          --ports 80 \
          --os-type Linux \
          --cpu 1 \
          --memory 1.5 \
          --secure-environment-variables DB_CONNECTION_STRING="${{ secrets.ACR_SQL_DB_CONNECTION_STRING }}" \
          --registry-login-server ${{ env.AZURE_CONTAINER_REGISTRY }} \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --location ${{ env.AZURE_ACI_REGION }}

        echo "--- Despliegue de ACI completado. Recuperando FQDN ---"
        ACI_FQDN=$(az container show --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_ACI_NAME }} --query "ipAddress.fqdn" -o tsv)
        echo "¡Tu aplicación estará disponible en: http://$ACI_FQDN"
        echo "aci_url=http://$ACI_FQDN" >> $GITHUB_OUTPUT

    - name: Mostrar URL de la aplicación desplegada
      run: echo '¡Tu aplicación está disponible en ${{ steps.deploy-aci.outputs.aci_url }}'
      if: success()
